version: 2

updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
  ignore:
    - dependency-name: "org.junit.*"
  labels:
    - "ğŸ“– theme: build"
    - "ğŸ›¸ 3rd-party: Gradle"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  labels:
    - "ğŸ“– theme: infrastructure"
    - "ğŸ›¸ 3rd-party: Github Actions"
