name: Main build

on:
  push:
    branches: 'master'
    tags-ignore: 
      - 'v**'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 15
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 8, 11, 14 ]
        os: [ubuntu, windows, macos]
    name: with Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          # fetch unshallow to enable blame for Sonar
          fetch-depth: 0
      - name: Set up java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Sonar
        uses: actions/cache@v2
        if: matrix.java == '11' && matrix.os == 'ubuntu'
        with:
          path: ~/.sonar/cache/
          key: ${{ runner.os }}-sonar
      - uses: burrunan/gradle-cache-action@v1
        name: Gradle build
        with:
          job-id: jdk${{ matrix.java }}
          arguments: --refresh-dependencies --stacktrace --scan clean build
      - uses: burrunan/gradle-cache-action@v1
        name: Sonar analysis
        if: matrix.java == '11' && matrix.os == 'ubuntu'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: "61ab2579215aa8a0024a2f9368fc1298fdecfd18"
        with:
          job-id: jdk${{ matrix.java }}
          arguments: jacocoTestReport sonarqube --stacktrace -i

  buildDone:
    name: buildOk
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: buildOk
        run: echo 'all builds passed'
