name: Module build on Java 11+

on:
  push:
    branches: 'master'
    tags-ignore:
      - 'v**'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 15
    strategy:
      matrix:
        # test against latest update of each major Java 11+ version, as well as specific updates of LTS versions:
        java: [ 11, 15 ]
        os: [ubuntu, macos]
    name: with Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Gradle
        uses: actions/cache@v2.1.4
        with:
          path: ~/.gradle/caches/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Gradle build on Java 11+
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -PmodularBuild --refresh-dependencies --stacktrace --scan clean build

  buildDone:
    name: buildOk
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: buildOk
        run: echo 'all builds passed'
